import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();
  // console.log(session?.user)
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col">
          {/* Make Navbar fixed */}
          <div className="fixed w-full z-10">
            <Navbar session={session} />
          </div>
          {/* Add padding to avoid overlapping */}
          <div className="relative pt-[4rem]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}

